<?php
class Router
{
  /**
   * Flag for REST url generation, supported value false.
   *
   * @todo Add true to support REST url generation.
   */
  const REST = false;

  /**
   * Run current controller action.
   *
   * @throws RouteNotFound if provided route is not found.
   *
   * @return void
   */
  public static function dispatch()
  {
    // WARNING: Do not use extract($_GET), it will expose security vulnerabilities
    $route = self::currentRoute();
    $controller_name = ucfirst($_GET['controller']) . "Controller";
    $action_name = strtolower($_GET['action']);

  	// WARNING: php do not support "new" as identifier, use neu (new in German) instead
  	if ($action_name == "new") $action_name = "neu";

    // INFO: make sure provided controller and action exist
    if (method_exists($controller_name, $action_name)) {
      $controller = new $controller_name();
      $controller->$action_name();        
    } else {
      throw new RouteNotFound($route);
    }
  }

  /**
   * Return current route generated by Router::routify().
   *
   * @see Router::routify for how route is generated.
   *
   * @return string
   */
  public static function currentRoute()
  {
    return self::routify($_GET['controller'], $_GET['action']);
  }

  /**
   * Return path of provided route.
   * 
   * @param string $route Route in format 'controller#action'
   *
   * @return string
   *
   * @todo Generate REST path.
   */
  public static function path_of($route) {
    list($controller, $action) = explode('#', $route);

    // TODO: Generate REST path
    if (!self::REST) return "index.php?controller=" . $controller . "&action=" . $action;
  }

  /**
   * Generate route
   *
   * @param string $controller
   * @param string $action
   *
   * @return string Routes
   */
  private static function routify($controller, $action)
  {
    return $controller . "#" . $action;
  }

  /**
   * Triggered when invoking inaccessible method in a static context.
   *
   * This function mainly used to generate url routes with function ends with _path,
   * such as call to Router::sessions_new_path() will generate url to path of new sessions.
   *
   * @param string $name Static method name
   * @param mixed[] $arguments Static method arguments in array
   *
   * @return string Generated path
   *
   * @todo Generate REST path
   */
  public static function __callStatic($name, $arguments)
  {
    list($controller, $action, $suffix) = explode('_', $name);

    // INFO: generate path if static method $name ends with _path
    if ($suffix == 'path') {
      // TODO: Generate REST path
      return self::path_of(self::routify($controller, $action));
    }
  }
}
